version: '3.8'

services:
    nginx:
        container_name: reverse-proxy-nginx
        restart: unless-stopped
        image: nginx:1.23.2-alpine
        volumes:
            - ./config/nginx.conf:/etc/nginx/nginx.conf:ro # nginx.conf
            - ./config/proxy_params.conf:/etc/nginx/proxy_params:ro # proxy params
            - ./config/sites:/etc/nginx/sites-enabled:ro # services
            - ./logs/:/var/log/nginx/:rw # logs
            - ./config/certbot/conf:/etc/letsencrypt
            - ./config/certbot/www:/var/www/certbot
        ports:
            - 80:80
            - 443:443
        networks:
            - reverse-proxy
        command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

    certbot:
        container_name: reverse-proxy-certbot
        restart: unless-stopped
        image: certbot/certbot:latest
        volumes:
            - ./config/certbot/conf:/etc/letsencrypt
            - ./config/certbot/www/:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
    reverse-proxy:
        name: reverse-proxy
